#!/bin/bash

set -eo pipefail

#
# This script prepares creates a new multidev environment on Pantheon.
# It should be run from Git branches other than the primary (master) branch
#

# Authenticate with Terminus
terminus -n auth:login --machine-token="$TERMINUS_TOKEN"

# Create the multidev environment
# The content and database are cloned from the dev environment
terminus -n multidev:create $TERMINUS_SITE.dev $TERMINUS_ENV