#!/bin/bash

set -eo pipefail

#
# This script runs cleanup after Behat tests complete.
#

# Authenticate with Terminus
terminus -n auth:login --machine-token="$TERMINUS_TOKEN"

# Restore the DB backup made before testing
terminus -n backup:restore $TERMINUS_SITE.$TERMINUS_ENV --element=database --yes

# Clear site cache
terminus -n env:clear-cache $TERMINUS_SITE.$TERMINUS_ENV