#!/bin/bash

# If we are testing against the dev environment, then we placed the
# environment in sftp mode and rsync'ed the build assets. In that
# instance, we will commit the build assets if testing the master branch
# of the GitHub repository (e.g. after a PR is merged).
if [ "$TERMINUS_ENV" == "dev" ]
then
  terminus --yes site code commit --message="Build assets for CI-$CIRCLE_BUILD_NUM."
  exit 0
fi

# Exit immediately on errors, and echo commands as they are executed.
set -ex

# Set the $PATH to include the global composer bin directory.
PATH=$PATH:~/.composer/vendor/bin

# Switch the dev site back to git mode. It should remain in git mode, though.
terminus site set-connection-mode --env=dev --mode=git

# Replace the entire contentsof the master branch with the branch we just tested.
git checkout master
git merge -q -m "Merge build assets from test CI-$CIRCLE_BUILD_NUM." -X theirs $TERMINUS_ENV

# Push our changes back to the dev environment, replacing whatever was there before.
git push --force -q pantheon master
