#!/bin/bash

if [ -z "$TERMINUS_SITE" ] || [ -z "$TERMINUS_ENV" ]
then
  echo 'No test site specified. Set TERMINUS_SITE and TERMINUS_ENV.'
  exit 1
fi

echo "::::::::::::::::::::::::::::::::::::::::::::::::"
echo "Behat test site: $TERMINUS_SITE.$TERMINUS_ENV"
echo "::::::::::::::::::::::::::::::::::::::::::::::::"
echo


# Reinstall WordPress before running tests.
# @todo, don't do this here, or at all.
terminus env:wipe $TERMINUS_SITE.$TERMINUS_ENV --yes

{
  terminus wp $TERMINUS_SITE.$TERMINUS_ENV -- core install --title=$TERMINUS_ENV-$TERMINUS_SITE --url=$PANTHEON_SITE_URL --admin_user=$WORDPRESS_ADMIN_USERNAME --admin_email=steve.persch@getpantheon.com --admin_password=$WORDPRESS_ADMIN_PASSWORD
} &> /dev/null

terminus wp $TERMINUS_SITE.$TERMINUS_ENV -- option update permalink_structure "/%postname%/"

# Exit immediately on errors, and echo commands as they are executed.
set -ex


export BEHAT_PARAMS='{"extensions" : {"Behat\\MinkExtension" : {"base_url" : "http://'$TERMINUS_ENV'-'$TERMINUS_SITE'.pantheonsite.io/wp"} }}'
cd tests && ../vendor/bin/behat --config=behat-pantheon.yml --strict "$@"
