#!/bin/bash

set -eo pipefail

#
# This script runs static tests which
# can be performed without code execution.
#
# Some example are code sniffing and unit testing
#

# Configure environment variables
/build-tools-ci/scripts/set-environment

# Run composer install to get the vendor directory
composer install

# Delete and reset the web directory
# This is necessary so that third-party
# dependencies are not tested
rm -rf web
git checkout -- web

# Lint php code for syntax errors
composer -n lint

# Check coding standards
composer -n code-sniff

# Run unit tests
composer -n unit-test